services:
  postgres-database:
    image: postgres
    container_name: 'api-cap-sync'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
    networks:
      - backend

networks:
  backend: